// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface User {
  /**
   * The role of the user in the app
   */
  role: "admin" | "user";
}

/**
 * A Polymarket wallet address being watched for the smart-wallet consensus system. Stores cached, synced stats — not the raw activity itself.
 */
export interface TrackedWallet {
  /**
   * Polymarket/Polygon wallet address (lowercased), e.g. 0xabc...
   */
  address: string;
  /**
   * Human-friendly nickname, defaults to the Polymarket username if known
   */
  label?: string;
  /**
   * Free-form research notes about why this wallet is being watched
   */
  notes?: string;
  /**
   * How this wallet was discovered
   */
  source?: "manual" | "leaderboard_pnl" | "leaderboard_vol";
  /**
   * Whether this wallet should be included in bulk syncs
   */
  is_active?: boolean;
  /**
   * Last time activity/positions were synced from Polymarket
   */
  last_synced_at?: string;
  /**
   * Outcome of the most recent sync attempt
   */
  last_sync_status?: "pending" | "success" | "error";
  /**
   * Error message from the most recent failed sync, if any
   */
  last_sync_error?: string;
  /**
   * Polymarket's own all-time realized+unrealized PnL for this wallet, from the leaderboard endpoint (0 if the wallet is unranked)
   */
  all_time_pnl_usd?: number;
  /**
   * Polymarket's own all-time trading volume for this wallet, from the leaderboard endpoint
   */
  all_time_volume_usd?: number;
  /**
   * Total distinct activity rows stored for this wallet
   */
  activity_count_synced?: number;
  /**
   * Number of distinct markets (condition IDs) seen in the synced activity
   */
  distinct_markets_synced?: number;
  /**
   * Number of currently open positions
   */
  open_positions_count?: number;
  /**
   * Current USD value of all open positions
   */
  open_positions_value_usd?: number;
  /**
   * Sum of cash PnL across all open positions
   */
  open_positions_unrealized_pnl_usd?: number;
  /**
   * Timestamp of the earliest activity row currently synced (bounded by API history depth)
   */
  first_synced_activity_at?: string;
  /**
   * Timestamp of the most recent activity row synced
   */
  last_synced_activity_at?: string;
}

/**
 * A single synced on-chain activity event (trade, split, merge, redeem, reward, conversion) for a tracked wallet.
 */
export interface WalletActivity {
  /**
   * Lowercased wallet address this event belongs to
   */
  wallet_address: string;
  /**
   * Type of on-chain activity
   */
  event_type: "TRADE" | "SPLIT" | "MERGE" | "REDEEM" | "REWARD" | "CONVERSION";
  /**
   * Trade side, only present for TRADE events
   */
  side?: "BUY" | "SELL";
  /**
   * Market question/title
   */
  market_title?: string;
  /**
   * Market slug on polymarket.com
   */
  market_slug?: string;
  /**
   * Polymarket condition ID for the market
   */
  condition_id?: string;
  /**
   * Outcome label, e.g. Yes/No
   */
  outcome?: string;
  /**
   * Index of the outcome traded
   */
  outcome_index?: number;
  /**
   * Execution price (0-1) at the time of the event
   */
  price?: number;
  /**
   * Size in shares/tokens
   */
  size?: number;
  /**
   * Size in USDC
   */
  usdc_size?: number;
  /**
   * When the event occurred on-chain
   */
  occurred_at: string;
  /**
   * On-chain transaction hash
   */
  transaction_hash?: string;
  /**
   * Deterministic key used to avoid re-inserting the same event on repeated syncs
   */
  dedupe_key: string;
}

/**
 * A snapshot of a currently open position for a tracked wallet. Replaced in full on every sync, so it always reflects the latest known state rather than history.
 */
export interface WalletPosition {
  /**
   * Lowercased wallet address this position belongs to
   */
  wallet_address: string;
  /**
   * Polymarket condition ID for the market
   */
  condition_id: string;
  /**
   * Market question/title
   */
  market_title?: string;
  /**
   * Market slug on polymarket.com
   */
  market_slug?: string;
  /**
   * Outcome label, e.g. Yes/No
   */
  outcome?: string;
  /**
   * Index of the outcome held
   */
  outcome_index?: number;
  /**
   * Shares/tokens held
   */
  size?: number;
  /**
   * Volume-weighted average entry price (0-1)
   */
  avg_price?: number;
  /**
   * Current market price (0-1)
   */
  current_price?: number;
  /**
   * USD cost basis of the position
   */
  initial_value_usd?: number;
  /**
   * Current USD value of the position
   */
  current_value_usd?: number;
  /**
   * Unrealized + realized cash PnL in USD
   */
  cash_pnl_usd?: number;
  /**
   * PnL as a percentage of cost basis
   */
  percent_pnl?: number;
  /**
   * Whether the position's market has resolved and can be redeemed
   */
  redeemable?: boolean;
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "User": User;
    "TrackedWallet": TrackedWallet;
    "WalletActivity": WalletActivity;
    "WalletPosition": WalletPosition;
  }
  
  interface FunctionNameRegistry {
    "polymarket-leaderboard": true;
    "sync-wallet": true;
    "sync-all-wallets": true;
  }
}